config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      current_user.update_last_seen
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @users = User.all
    end
  end

  def help
    if logged_in?
      current_user.update_last_seen
    end
  end

  def about
    if logged_in?
      current_user.update_last_seen
    end
  end

  def contact
    if logged_in?
      current_user.update_last_seen
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="well animated bounceInUp">
  <h1 id="coolify-title" class="animated zoomInDown">About</h1>
  <p>
    Hello, and thanks for visiting! Poppin is my version of the Sample App from 
    Michael Hartl's
    <a href="http://www.railstutorial.org/" target="_blank"><em>Ruby on Rails
    Tutorial</em></a>. I created Poppin in March 2016 as a project for Robeen Dey's 
    <a href="https://codermanual.com/" target="_blank">Coder Manual</a> coding 
    bootcamp. I highly recommend these resources to anyone looking to learn 
    web development.
  </p>
  
  <p>
    There are a few rules I'd like you to follow to keep Poppin fun for everyone:
  </p>
  <ol>
    <li>No profanity</li>
    <li>No obscene profile images, language, etc.</li>
    <li>No spamming, trolling, threatening, etc.</li>
    <li>Above all, be nice to each other (please)</li>
  </ol>
  <p>
    If I see anything (or recieve reports about anything) that could 
    cause a disturbance of the peace, I'll give a 
    warning to the person(s) involved and do my best to try to solve the 
    problem. If the behavior continues, I may have to delete the problematic 
    Pops (or even the entire accounts involved). If it somehow persists after 
    that, I will send a note home to your parents and put you in the corner 
    for a time-out.
  </p>
  
  <p>
    Anyways, just don't Pop anything you wouldn't want Mom, the Pentagon, or 
    Jesus to see. Besides, all moms have mother's intuition (and can tell when 
    you're getting into trouble), the Pentagon is probably monitoring 
    your Pops right now, and Jesus is, well, omniscient (to say the least).
  </p>
  
  <p>
    Special thanks to users 
    <a href="https://warm-temple-79460.herokuapp.com/users/102" target="_blank">Sydney Barta</a>,
    <a href="https://warm-temple-79460.herokuapp.com/users/103" target="_blank">Gabriela</a>,
    <a href="https://warm-temple-79460.herokuapp.com/users/104" target="_blank">ginna_rosie</a>,
    and 
    <a href="https://warm-temple-79460.herokuapp.com/users/109" target="_blank">Joshua Newton</a>
    for their awesome theme ideas, and to user 
    <a href="https://warm-temple-79460.herokuapp.com/users/111" target="_blank">Kiara</a> for 
    the awesome 
    <a href="http://kakaunolakouiailalo.blogspot.com/2016/03/poppin.html" target="_blank">write-up!</a> 
    Check out her blog 
    <a href="http://kakaunolakouiailalo.blogspot.com" target="_blank">here</a>.
  </p>
  
  <p>
    Major props to my little brother 
    <a href="https://warm-temple-79460.herokuapp.com/users/110">Evan Acosta</a> 
    for coding in all those steezy animations!
  </p>
  
  <p>
    <i>
      Tyler Acosta is a Catholic, a 
      <a href="https://www.youtube.com/channel/UCoCUaN6pEJ5i09_zbhR8uYQ" target="_blank">musician</a>, 
      an aspiring web developer, 
      a homeschooler, and a tennis player in Springfield, Missouri. He enjoys 
      popcorn, playing piano/melodica/keytar/anything that has keys, 
      rollerblading, and a lot of other things too. If you've logged in, you 
      can check out his Kernel 
      <a href="https://warm-temple-79460.herokuapp.com/users/101">here</a>.
    </i>
  </p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="well animated bounceInUp">
  <h1 id="coolify-title" class="animated zoomInDown">Contact</h1>
  <p>
    Send all your questions, comments, suggestions, monies, etc. to Tyler Acosta at 
    <a href="mailto:tacos1998@gmail.com">tacos1998@gmail.com</a>.
  </p>
  
  <p>
    In addition to being a web developer. Tyler is also a 
    <a href="https://www.gigsalad.com/tyler_acosta_springfield" target="_blank">performing</a> 
    <a href="https://www.youtube.com/channel/UCoCUaN6pEJ5i09_zbhR8uYQ" target="_blank">musician</a>, 
    competitive tennis player, and rigorous scholar, who needs all the cash he 
    can get to save for college. Please contact him using the 
    above email address for gig/booking inquiries, 
    music lesson info (piano/recording software training), tennis lesson info, 
    racquet stringing services, tutoring, and any other work/performance 
    opportunities.
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="well animated bounceInUp">
  <h1 id="coolify-title" class="animated zoomInDown">Help</h1>
  <h2>
    <a href="https://youtu.be/5kHQ0AhkDnU?t=6" target="_blank">(I need somebody!)</a>
  </h2>
  
  <h3>Welcome to Poppin!</h3>
  
  <p>
    Hello! This guide will show you the in's and out's of Poppin. Let's begin 
    by getting you familiar with the basic site layout.
  </p>
  
  <p>
    At the top of your screen is the <strong>Navbar</strong>. It contains the 
    stylish Poppin logo (click it to return home at any time), as well as links 
    to the <strong>Home</strong> and <strong>Help</strong> pages. If you haven't logged in, there will be a 
    <strong>Pop in</strong> link for you to do so. If you have logged in, there 
    will also be links to <strong>The Popper</strong> and your <strong>Nibbles</strong> (keep reading), 
    as well as the
    <strong>Account</strong> dropdown menu, with links to view your 
    <strong>Kernel</strong> (more on that later), edit your account 
    <strong>Settings</strong>, or log out (<strong>Pop out</strong>).
  </p>
  
  <p>
    If you're using Poppin on a mobile device (or other small screen), 
    the aforementioned links will be replaced with a button. Tap/click it to expand 
    the navbar in dropdown form.
  </p>
  
  <p>
    At the bottom of your screen is the footer, which has 
    links to the <strong>About</strong>, <strong>Contact</strong>, 
    and <strong>Other</strong> pages. There's also a shiny gold button, 
    I wonder what would happen if you clicked on it?...
  </p>
  
  <h3>Getting Started</h3>
  
  <p>
    Before you create an Poppin account, you should use <strong><a href="https://en.gravatar.com/" target="_blank">Gravatar</a></strong> 
    to link a profile picture with your email address. Simply create a Gravatar/Wordpress account with your email 
    (the same one you'll use for your Poppin account), check your inbox for an 
    activation link, click it, select an image, and you'll be ready to go.
  </p>
  
  <p>
    To create your account, visit 
    the <strong><%= link_to "signup page", new_user_path, target: '_blank' %></strong> and enter 
    a username, email, and password. Once you hit the submit button, you should recieve a new confirmation email that 
    contains your Poppin activation link. Check your inbox, click on the link in the email, and you'll be directed to 
    your Kernel.
  </p>
  
  <p>
    Your <strong>Kernel</strong> is your profile page. It displays your username, Gravatar, and all 
    of your <strong>Pops</strong>, along with a button at the top for people to <strong>Crunch</strong> or 
    <strong>Uncrunch</strong> you. This is what other users will see when they click on you. 
    Once you've logged in, you can view your Kernel by clicking the 
    <strong>My Kernel</strong> link in the navbar's Account dropdown menu (top right corner).
  </p>
  
  <p>
    Once you've activated your account and logged in, navigate to the Home page 
    (click the Poppin logo or the Home link in the navbar) to view your 
    <strong>Pop Box</strong>. This is where you 
    can Pop and view a feed of Pops from yourself and from the users you're 
    crunching. There's also a <strong>Now Playing</strong> button that will display 
    the Gravatars/Kernel links of all online users.
  </p>
  
  <p>
    <strong>Pops</strong> are the heart and soul of Poppin. You can Pop whatever you like, as 
    long as you stay under 200 characters and follow <%= link_to "the rules", about_path %>. 
    <br><i>Protip: type the @ symbol in the Pop textbox to bring up a menu of usernames (if you want to mention people in your Pop).</i>
  </p>
  
  <p>
    If you find a Pop from another user that you particularly enjoy, you 
    should <strong>Savor</strong> it! Just hit that Savor button and that Pop's Savor count will 
    increase. Also, your Gravatar (which links to your Kernel) will be added 
    to the list of Savorers (which can be accessed by clicking the "# savors" button).
  </p>
  
  <p>
    <strong>The Popper</strong> (link is in the navbar if you've logged in) is a 
    roster of all activated users. Click on a user to view their Kernel. Near 
    the top of the page is a button for you to <strong>Crunch</strong> (follow) the user so that their Pops 
    will show up in your Pop Box, or to <strong>Uncrunch</strong> (unfollow) 
    the user if you're already Crunching them.
  </p>
  
  <p>
    Also displayed in the Kernel is a curious-looking <strong>Nibble</strong> buttton. 
    Nibble is Poppin's private messaging system. The main Nibble menu can be accessed 
    via the Nibble link in the navbar. This menu consists of three folders: 
    the inbox, which shows all active Nibbles (from here you can mark a Nibble 
    as read or move it to the trash); the sent folder, which displays 
    all sent Nibbles; and the trash folder, which includes all trashed nibbles (and 
    a button to empty the trash and delete them permanently). The number of 
    unread Nibbles (if any) will be displayed alongside the Nibbles link in the navbar.
  </p>
  
  <p>
    Nibbles can only be 
    viewed by the sender and recipient(s). You can specify as many recipients as you like, 
    and (unlike Pops) there is no character limit. And (rewinding to what was said earlier) 
    clicking the Nibble button on a user's Kernel will compose a new Nibble with 
    the user as the recipient. You will recieve an email notification whenever you 
    are Nibbled or whenever someone replies to one of your Nibbles.
  </p>
  
  <p>
    In general, if you have a short thought that you want to express to everyone, Pop it! 
    If you want to direct a longer message towards a specific person or group 
    of people, Nibble it!
  </p>

  <p>
    If you have any questions, comments, feedback, suggestions, or bugs to 
    report, please contact the admin at 
    <a href="mailto:tacos1998@gmail.com">tacos1998@gmail.com</a> for assistance.
  </p>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="well row main animated fadeIn">
    <aside class="col-md-4 animated bounceInUp">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="well col-md-8 animated fadeIn">
      <h3 id="popbox">Pop Box <%= render 'shared/now_playing' %></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron animated bounceInUp">
    <h1 id="coolify" class="animated zoomInDown">POPPIN</h1>

    <h2>
      Pop your thoughts. Crunch your friends. Add salt to taste.
    </h2>

    <%= link_to "Let's get Poppin!", login_path, class: "btn btn-lg btn-primary" %>
    <h2 id="n00bz">
      New to Poppin? Check out the <%= link_to "Help", help_path %> page to get started!
    </h2>
  </div>

  <!-- <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %> -->
<% end %>